---
    url: "http://192.168.99.101:8080"
    database: 
        host: "192.168.99.101"
        dbname: "nflix"
        user: "postgres"
        password: "qaninja"
    users:
        cat_manager:
            email: "tony@stark.com"
            pass: "pwd123"
        admin:
            email: "Admin@stark.com"
            pass: "admin123"