---
    url: "http://hmg.nflix.com"
    database: 
        host: "192.168.99.101"
        dbname: "nflix"
        user: "postgres"
        password: "qaninja"
    users:
        cat_manager:
            email: "peper.posts@stark.com"
            pass: "pwd123"